
package ConsomationReservationChambreAgence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationChambreAvecAgenceImplService", targetNamespace = "http://ServiceImpl/", wsdlLocation = "http://localhost:8080/service-reservation-chambre-agence?wsdl")
public class ReservationChambreAvecAgenceImplService
    extends Service
{

    private final static URL RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_EXCEPTION;
    private final static QName RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_QNAME = new QName("http://ServiceImpl/", "ReservationChambreAvecAgenceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service-reservation-chambre-agence?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_WSDL_LOCATION = url;
        RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_EXCEPTION = e;
    }

    public ReservationChambreAvecAgenceImplService() {
        super(__getWsdlLocation(), RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_QNAME);
    }

    public ReservationChambreAvecAgenceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_QNAME, features);
    }

    public ReservationChambreAvecAgenceImplService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_QNAME);
    }

    public ReservationChambreAvecAgenceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_QNAME, features);
    }

    public ReservationChambreAvecAgenceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationChambreAvecAgenceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationChambreAvecAgence
     */
    @WebEndpoint(name = "ReservationChambreAvecAgenceImplPort")
    public ReservationChambreAvecAgence getReservationChambreAvecAgenceImplPort() {
        return super.getPort(new QName("http://ServiceImpl/", "ReservationChambreAvecAgenceImplPort"), ReservationChambreAvecAgence.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationChambreAvecAgence
     */
    @WebEndpoint(name = "ReservationChambreAvecAgenceImplPort")
    public ReservationChambreAvecAgence getReservationChambreAvecAgenceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceImpl/", "ReservationChambreAvecAgenceImplPort"), ReservationChambreAvecAgence.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_EXCEPTION!= null) {
            throw RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_EXCEPTION;
        }
        return RESERVATIONCHAMBREAVECAGENCEIMPLSERVICE_WSDL_LOCATION;
    }

}
