
package ConsomationRechercheChambreAgence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RechercheChambreAgenceImplService", targetNamespace = "http://ServiceImpl/", wsdlLocation = "http://localhost:8080/service-recherche-chambre-agence?wsdl")
public class RechercheChambreAgenceImplService
    extends Service
{

    private final static URL RECHERCHECHAMBREAGENCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECHERCHECHAMBREAGENCEIMPLSERVICE_EXCEPTION;
    private final static QName RECHERCHECHAMBREAGENCEIMPLSERVICE_QNAME = new QName("http://ServiceImpl/", "RechercheChambreAgenceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service-recherche-chambre-agence?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECHERCHECHAMBREAGENCEIMPLSERVICE_WSDL_LOCATION = url;
        RECHERCHECHAMBREAGENCEIMPLSERVICE_EXCEPTION = e;
    }

    public RechercheChambreAgenceImplService() {
        super(__getWsdlLocation(), RECHERCHECHAMBREAGENCEIMPLSERVICE_QNAME);
    }

    public RechercheChambreAgenceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECHERCHECHAMBREAGENCEIMPLSERVICE_QNAME, features);
    }

    public RechercheChambreAgenceImplService(URL wsdlLocation) {
        super(wsdlLocation, RECHERCHECHAMBREAGENCEIMPLSERVICE_QNAME);
    }

    public RechercheChambreAgenceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECHERCHECHAMBREAGENCEIMPLSERVICE_QNAME, features);
    }

    public RechercheChambreAgenceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RechercheChambreAgenceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RechercheChambreAgence
     */
    @WebEndpoint(name = "RechercheChambreAgenceImplPort")
    public RechercheChambreAgence getRechercheChambreAgenceImplPort() {
        return super.getPort(new QName("http://ServiceImpl/", "RechercheChambreAgenceImplPort"), RechercheChambreAgence.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RechercheChambreAgence
     */
    @WebEndpoint(name = "RechercheChambreAgenceImplPort")
    public RechercheChambreAgence getRechercheChambreAgenceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceImpl/", "RechercheChambreAgenceImplPort"), RechercheChambreAgence.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECHERCHECHAMBREAGENCEIMPLSERVICE_EXCEPTION!= null) {
            throw RECHERCHECHAMBREAGENCEIMPLSERVICE_EXCEPTION;
        }
        return RECHERCHECHAMBREAGENCEIMPLSERVICE_WSDL_LOCATION;
    }

}
