
package ConsomationRechercheChambreAgence;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RechercheChambreAgence", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RechercheChambreAgence {


    /**
     * 
     * @param prixMin
     * @param prixMax
     * @param nbLit
     * @return
     *     returns java.util.List<ConsomationRechercheChambreAgence.Chambre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherChambresAgence", targetNamespace = "http://Service/", className = "ConsomationRechercheChambreAgence.RechercherChambresAgence")
    @ResponseWrapper(localName = "rechercherChambresAgenceResponse", targetNamespace = "http://Service/", className = "ConsomationRechercheChambreAgence.RechercherChambresAgenceResponse")
    @Action(input = "http://Service/RechercheChambreAgence/rechercherChambresAgenceRequest", output = "http://Service/RechercheChambreAgence/rechercherChambresAgenceResponse")
    public List<Chambre> rechercherChambresAgence(
        @WebParam(name = "prixMin", targetNamespace = "")
        int prixMin,
        @WebParam(name = "prixMax", targetNamespace = "")
        int prixMax,
        @WebParam(name = "nbLit", targetNamespace = "")
        int nbLit);

}
