
package ConsomationRechercheChambre;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RechercheChambreHotelImplService", targetNamespace = "http://ServiceImpl/", wsdlLocation = "http://localhost:8080/service-recherche-chambre-kyriad?wsdl")
public class RechercheChambreHotelImplService
    extends Service
{

    private final static URL RECHERCHECHAMBREHOTELIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECHERCHECHAMBREHOTELIMPLSERVICE_EXCEPTION;
    private final static QName RECHERCHECHAMBREHOTELIMPLSERVICE_QNAME = new QName("http://ServiceImpl/", "RechercheChambreHotelImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service-recherche-chambre-kyriad?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECHERCHECHAMBREHOTELIMPLSERVICE_WSDL_LOCATION = url;
        RECHERCHECHAMBREHOTELIMPLSERVICE_EXCEPTION = e;
    }

    public RechercheChambreHotelImplService() {
        super(__getWsdlLocation(), RECHERCHECHAMBREHOTELIMPLSERVICE_QNAME);
    }

    public RechercheChambreHotelImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECHERCHECHAMBREHOTELIMPLSERVICE_QNAME, features);
    }

    public RechercheChambreHotelImplService(URL wsdlLocation) {
        super(wsdlLocation, RECHERCHECHAMBREHOTELIMPLSERVICE_QNAME);
    }

    public RechercheChambreHotelImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECHERCHECHAMBREHOTELIMPLSERVICE_QNAME, features);
    }

    public RechercheChambreHotelImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RechercheChambreHotelImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RechercheChambreHotel
     */
    @WebEndpoint(name = "RechercheChambreHotelImplPort")
    public RechercheChambreHotel getRechercheChambreHotelImplPort() {
        return super.getPort(new QName("http://ServiceImpl/", "RechercheChambreHotelImplPort"), RechercheChambreHotel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RechercheChambreHotel
     */
    @WebEndpoint(name = "RechercheChambreHotelImplPort")
    public RechercheChambreHotel getRechercheChambreHotelImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceImpl/", "RechercheChambreHotelImplPort"), RechercheChambreHotel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECHERCHECHAMBREHOTELIMPLSERVICE_EXCEPTION!= null) {
            throw RECHERCHECHAMBREHOTELIMPLSERVICE_EXCEPTION;
        }
        return RECHERCHECHAMBREHOTELIMPLSERVICE_WSDL_LOCATION;
    }

}
