
package ConsomationReservationChambre;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationChambreImplService", targetNamespace = "http://ServiceImpl/", wsdlLocation = "http://localhost:8080/service-reservation-chambre?wsdl")
public class ReservationChambreImplService
    extends Service
{

    private final static URL RESERVATIONCHAMBREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONCHAMBREIMPLSERVICE_EXCEPTION;
    private final static QName RESERVATIONCHAMBREIMPLSERVICE_QNAME = new QName("http://ServiceImpl/", "ReservationChambreImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service-reservation-chambre?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONCHAMBREIMPLSERVICE_WSDL_LOCATION = url;
        RESERVATIONCHAMBREIMPLSERVICE_EXCEPTION = e;
    }

    public ReservationChambreImplService() {
        super(__getWsdlLocation(), RESERVATIONCHAMBREIMPLSERVICE_QNAME);
    }

    public ReservationChambreImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONCHAMBREIMPLSERVICE_QNAME, features);
    }

    public ReservationChambreImplService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONCHAMBREIMPLSERVICE_QNAME);
    }

    public ReservationChambreImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONCHAMBREIMPLSERVICE_QNAME, features);
    }

    public ReservationChambreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationChambreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationChambre
     */
    @WebEndpoint(name = "ReservationChambreImplPort")
    public ReservationChambre getReservationChambreImplPort() {
        return super.getPort(new QName("http://ServiceImpl/", "ReservationChambreImplPort"), ReservationChambre.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationChambre
     */
    @WebEndpoint(name = "ReservationChambreImplPort")
    public ReservationChambre getReservationChambreImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceImpl/", "ReservationChambreImplPort"), ReservationChambre.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONCHAMBREIMPLSERVICE_EXCEPTION!= null) {
            throw RESERVATIONCHAMBREIMPLSERVICE_EXCEPTION;
        }
        return RESERVATIONCHAMBREIMPLSERVICE_WSDL_LOCATION;
    }

}
