
package ConsomationReservationChambre;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationChambre", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationChambre {


    /**
     * 
     * @param numChambre
     * @param dateArrive
     * @param dateDepart
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://Service/", className = "ConsomationReservationChambre.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://Service/", className = "ConsomationReservationChambre.ReserverChambreResponse")
    @Action(input = "http://Service/ReservationChambre/reserverChambreRequest", output = "http://Service/ReservationChambre/reserverChambreResponse")
    public String reserverChambre(
        @WebParam(name = "numChambre", targetNamespace = "")
        int numChambre,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "dateArrive", targetNamespace = "")
        String dateArrive,
        @WebParam(name = "dateDepart", targetNamespace = "")
        String dateDepart);

}
